# Generated by Django 5.0 on 2026-07-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "numero_processo",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Número do Processo",
                    ),
                ),
                (
                    "advogados_polo_ativo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Advogados Polo Ativo"
                    ),
                ),
                (
                    "advogados_polo_passivo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Advogados Polo Passivo"
                    ),
                ),
                (
                    "assuntos",
                    models.TextField(blank=True, null=True, verbose_name="Assuntos"),
                ),
                (
                    "classe",
                    models.TextField(blank=True, null=True, verbose_name="Classe"),
                ),
                (
                    "cnpjs",
                    models.TextField(blank=True, null=True, verbose_name="CNPJs"),
                ),
                (
                    "partes_polo_ativo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Partes Polo Ativo"
                    ),
                ),
                (
                    "partes_polo_passivo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Partes Polo Passivo"
                    ),
                ),
                (
                    "nome_cpf",
                    models.TextField(blank=True, null=True, verbose_name="Nome / CPF"),
                ),
                (
                    "comarca",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Comarca"
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="UF"
                    ),
                ),
                ("vara", models.TextField(blank=True, null=True, verbose_name="Vara")),
                (
                    "tribunal",
                    models.TextField(blank=True, null=True, verbose_name="Tribunal"),
                ),
                (
                    "data_distribuicao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Data da Distribuição",
                    ),
                ),
                (
                    "data_arquivamento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Data do Arquivamento",
                    ),
                ),
                (
                    "data_transito_julgado",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Data do Trânsito em Julgado",
                    ),
                ),
                (
                    "data_sentenca",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Data da Sentença",
                    ),
                ),
                (
                    "data_primeiro_acordao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Data do Primeiro Acórdão",
                    ),
                ),
                (
                    "data_acordo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Data do Acordo"
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Fase"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Situação"
                    ),
                ),
                (
                    "instancia",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Instância"
                    ),
                ),
                (
                    "juizes",
                    models.TextField(blank=True, null=True, verbose_name="Juízes"),
                ),
                (
                    "tipo_cargos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tipo de Cargos"
                    ),
                ),
                (
                    "desfecho",
                    models.TextField(blank=True, null=True, verbose_name="Desfecho"),
                ),
                (
                    "decisoes_por_instancia",
                    models.TextField(
                        blank=True, null=True, verbose_name="Decisões por Instância"
                    ),
                ),
                (
                    "tipos_recursos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tipos de Recursos"
                    ),
                ),
                (
                    "tipo_alteracao_condenacao",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Tipo de Alteração da Condenação",
                    ),
                ),
                (
                    "pedidos",
                    models.TextField(blank=True, null=True, verbose_name="Pedidos"),
                ),
                (
                    "indicativo_bloqueio",
                    models.TextField(
                        blank=True, null=True, verbose_name="Indicativo de Bloqueio"
                    ),
                ),
                (
                    "indicativo_revelia",
                    models.TextField(
                        blank=True, null=True, verbose_name="Indicativo de Revelia"
                    ),
                ),
                (
                    "valor_causa",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Valor de Causa (R$)",
                    ),
                ),
                (
                    "valor_condenacao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Valor de Condenação (R$)",
                    ),
                ),
                (
                    "valor_acordo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valor de Acordo (R$)"
                    ),
                ),
                (
                    "valor_liquidacao",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Valor de Liquidação (R$)"
                    ),
                ),
                (
                    "valor_depositos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valor de Depósitos (R$)"
                    ),
                ),
                (
                    "valor_variacao_condenacao",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Valor de Variação da Condenação (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo",
                "verbose_name_plural": "Processos",
                "db_table": "processos",
                "managed": True,
            },
        ),
    ]
