# Generated by Django 5.0 on 2026-07-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nome canônico"
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Grafias alternativas"
                    ),
                ),
                (
                    "ocorrencias_base",
                    models.IntegerField(
                        default=0, verbose_name="Ocorrências na planilha-base"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "criado_por_ia",
                    models.BooleanField(default=False, verbose_name="Sugerido pela IA"),
                ),
            ],
            options={
                "verbose_name": "Pedido (catálogo)",
                "verbose_name_plural": "Pedidos (catálogo)",
                "db_table": "pedidos_catalogo",
            },
        ),
        migrations.CreateModel(
            name="SincronizacaoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comando", models.CharField(max_length=60)),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("fim", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="executando", max_length=20)),
                ("detalhes", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Log de Sincronização",
                "verbose_name_plural": "Logs de Sincronização",
                "db_table": "sincronizacao_logs",
                "ordering": ["-inicio"],
            },
        ),
        migrations.AddField(
            model_name="processo",
            name="cnj_normalizado",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=25,
                null=True,
                verbose_name="CNJ (somente dígitos)",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="controljus_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                null=True,
                unique=True,
                verbose_name="ID ControlJus",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="data_admissao_demissao",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Data de Admissão / Demissão",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="data_ultimo_movimento",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Data do Último Movimento",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="deve_reembolso",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Deve Reembolso?"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="justica_gratuita",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Justiça Gratuita?"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="origem",
            field=models.CharField(
                default="planilha", max_length=20, verbose_name="Origem do registro"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="pagamentos_recursos",
            field=models.TextField(
                blank=True, null=True, verbose_name="Pagamentos de Recursos"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="possui_pedido_substituicao",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Possui Pedido de Substituição",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="segredo_justica",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Segredo de Justiça?"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="tipo_pedido_valor_desfecho",
            field=models.TextField(
                blank=True, null=True, verbose_name="TipoPedido / Valor / Desfecho"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="ultima_analise_ia",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Análise IA"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="ultima_sincronizacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Sincronização"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="ultimo_movimento",
            field=models.TextField(
                blank=True, null=True, verbose_name="Último Movimento"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="ultimo_salario",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Último Salário"
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="valor_custas",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Valor de Custas (R$)",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="valor_diferenca_custas",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Valor de Diferença de Custas (R$)",
            ),
        ),
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("andamento_id", models.BigIntegerField(db_index=True, unique=True)),
                (
                    "data_hora",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("nome", models.TextField(blank=True, default="")),
                (
                    "tipo_andamento",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "descricao_fonte",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "recorte_texto",
                    models.TextField(
                        blank=True, default="", verbose_name="Texto do recorte (DJEN)"
                    ),
                ),
                (
                    "recorte_diario",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "recorte_disponibilizacao",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("importado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="core.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "db_table": "movimentacoes",
            },
        ),
        migrations.CreateModel(
            name="Decisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_ato",
                    models.CharField(
                        choices=[
                            ("sentenca", "Sentença"),
                            ("acordao", "Acórdão"),
                            ("decisao", "Decisão"),
                            ("despacho", "Despacho"),
                            ("homologacao_acordo", "Homologação de Acordo"),
                            ("embargos", "Embargos de Declaração"),
                            ("transito", "Trânsito em Julgado"),
                            ("arquivamento", "Arquivamento"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "grau",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Grau/Instância"
                    ),
                ),
                (
                    "texto",
                    models.TextField(
                        blank=True, default="", verbose_name="Íntegra disponível"
                    ),
                ),
                (
                    "fonte_texto",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Fonte do texto",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Resultado inferido",
                    ),
                ),
                (
                    "analise_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Análise estruturada da IA"
                    ),
                ),
                (
                    "status_analise",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("analisado", "Analisado"),
                            ("sem_texto", "Sem texto disponível"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("modelo_ia", models.CharField(blank=True, default="", max_length=60)),
                ("data_analise", models.DateTimeField(blank=True, null=True)),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisoes",
                        to="core.processo",
                    ),
                ),
                (
                    "movimentacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisoes",
                        to="core.movimentacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decisão",
                "verbose_name_plural": "Decisões",
                "db_table": "decisoes",
            },
        ),
        migrations.CreateModel(
            name="PedidoProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_original",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nome como apareceu na fonte",
                    ),
                ),
                (
                    "valor_pleiteado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("PLEITEADO", "Pleiteado"),
                            ("DEFERIMENTO", "Deferimento"),
                            ("INDEFERIMENTO", "Indeferimento"),
                            ("DEFERIMENTO PARCIAL", "Deferimento Parcial"),
                            ("INDETERMINADO", "Indeterminado"),
                        ],
                        default="PLEITEADO",
                        max_length=25,
                    ),
                ),
                (
                    "instancia",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Instância da decisão"
                    ),
                ),
                (
                    "fundamentacao",
                    models.TextField(
                        blank=True, default="", verbose_name="Fundamentação resumida"
                    ),
                ),
                (
                    "confianca_ia",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Confiança da IA (0-1)"
                    ),
                ),
                (
                    "fonte",
                    models.CharField(
                        default="planilha",
                        max_length=30,
                        verbose_name="Fonte (planilha/ia/manual)",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos",
                        to="core.pedidocatalogo",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_norm",
                        to="core.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido do Processo",
                "verbose_name_plural": "Pedidos dos Processos",
                "db_table": "pedidos_processo",
            },
        ),
        migrations.AddIndex(
            model_name="movimentacao",
            index=models.Index(
                fields=["processo", "data_hora"], name="movimentaco_process_dbaab4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decisao",
            index=models.Index(
                fields=["processo", "tipo_ato"], name="decisoes_process_a66281_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pedidoprocesso",
            unique_together={("processo", "catalogo")},
        ),
    ]
